<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import { RouterLink } from 'vue-router'
import { todayKey } from '@/core/storage'
import { feishuWorkspace } from '@/domain/feishu/workspace-instance'
import { watchFeishuWorkspace, type WorkspaceSnapshot } from '@/core/feishu/workspace'
import { readTodayReferences, writeTodayReferences, boundField, fieldValue, relationIds, statusOptions, valueText, type FieldRole } from '@/core/feishu/model'
import type { FeishuRecord } from '@/core/api/feishu'
import CalmySelect from '@/vue/components/CalmySelect.vue'

const date=todayKey();const snapshot=ref<WorkspaceSnapshot>(feishuWorkspace.getSnapshot());const ids=ref<string[]>([]);const query=ref('');const draft=ref('');const projectId=ref('');const message=ref('');let stop:(()=>void)|undefined
function field(record:FeishuRecord,role:FieldRole,table='tasks' as const):unknown{return fieldValue(record,snapshot.value.fields[table]||[],snapshot.value.bindings[table]||{},role)}
function label(record:FeishuRecord,role:FieldRole):string{const raw=field(record,role);const target=role==='project'?'projects':role==='owner'?'members':null;if(target){const names=relationIds(raw).map(id=>{const item=snapshot.value.tables[target].find(candidate=>candidate.record_id===id);return item?valueText(fieldValue(item,snapshot.value.fields[target]||[],snapshot.value.bindings[target]||{},'title'))||id:id});if(names.length)return names.join('、')}return valueText(raw)}
function title(record:FeishuRecord):string{return label(record,'title')||'标题字段未识别'}
function read(){ids.value=snapshot.value.workspaceId?readTodayReferences(localStorage,snapshot.value.workspaceId,date):[]}
function save(next:string[]){try{writeTodayReferences(localStorage,snapshot.value.workspaceId,date,next);ids.value=next.slice(0,3);window.dispatchEvent(new Event('calmy-feishu-today'));message.value=''}catch{message.value='今日选择未保存：浏览器无法写入本机设置。'}}
const selected=computed(()=>ids.value.flatMap(id=>{const record=snapshot.value.tables.tasks.find(item=>item.record_id===id);return record?[record]:[]}))
const candidates=computed(()=>snapshot.value.tables.tasks.filter(record=>!ids.value.includes(record.record_id)&&label(record,'status')!=='已完成'&&(!query.value.trim()||title(record).toLowerCase().includes(query.value.trim().toLowerCase()))))
const missing=computed(()=>snapshot.value.ready?ids.value.filter(id=>!snapshot.value.tables.tasks.some(record=>record.record_id===id)):[])
const titleField=computed(()=>boundField(snapshot.value.fields.tasks||[],snapshot.value.bindings.tasks||{},'title'))
const projectField=computed(()=>boundField(snapshot.value.fields.tasks||[],snapshot.value.bindings.tasks||{},'project'))
const selectableStatuses=computed(()=>statusOptions(snapshot.value.fields.tasks||[],snapshot.value.bindings.tasks||{},snapshot.value.tables.tasks))
const projectOptions=computed(()=>[{value:'',label:'不关联项目'},...snapshot.value.tables.projects.map(record=>({value:record.record_id,label:valueText(fieldValue(record,snapshot.value.fields.projects||[],snapshot.value.bindings.projects||{},'title'))||record.record_id}))])
function taskStatusOptions(record:FeishuRecord){const current=label(record,'status')||'未设置';const fieldInfo=boundField(snapshot.value.fields.tasks||[],snapshot.value.bindings.tasks||{},'status');const available=fieldInfo?.type===3?fieldInfo.property?.options?.map(option=>option.name)||[]:selectableStatuses.value;return [...new Set([current,...available])].map(value=>({value,label:value,disabled:!available.includes(value)}))}
function statusText(){const s=snapshot.value;const cache=s.cacheUpdatedAt?new Date(s.cacheUpdatedAt).toLocaleString('zh-CN'):'';return s.saving?'正在写入飞书…':s.loading?cache?`正在检查更新 · 当前显示 ${cache} 的本机缓存`:'正在连接飞书并读取数据…':s.error?cache?`飞书暂不可用 · 当前显示 ${cache} 的本机缓存（只读）`:'飞书未连接，尚无本机缓存':s.usingCache&&cache?`部分数据来自本机缓存 · ${cache}`:s.lastRead?`上次读取 ${new Date(s.lastRead).toLocaleTimeString('zh-CN')}`:'尚未读取飞书数据'}
function dateText(raw:unknown){if(raw==null||raw==='')return '无截止日期';const text=valueText(raw);const date=new Date(/^\d+$/.test(text)?Number(text):text);return Number.isNaN(date.getTime())?text:date.toLocaleDateString('zh-CN')}
async function changeStatus(record:FeishuRecord,status:string){try{await feishuWorkspace.changeStatus(record.record_id,status)}catch(cause){window.dispatchEvent(new CustomEvent('beryl-toast',{detail:{message:cause instanceof Error?cause.message:'飞书状态更新失败',kind:'error'}}))}}
async function create(){if(!draft.value.trim()||!titleField.value||!snapshot.value.ready||snapshot.value.saving)return;message.value='';try{const id=await feishuWorkspace.createTask(draft.value,projectId.value);draft.value='';projectId.value='';if(ids.value.length>=3){message.value='任务已保存到飞书。今天已选了 3 项；可到今天调整选择。';return}save([...ids.value,id]);message.value='任务已保存到飞书并加入今天。'}catch(cause){message.value=cause instanceof Error?cause.message:'任务保存未确认';window.dispatchEvent(new CustomEvent('beryl-toast',{detail:{message:'飞书保存未确认，输入已保留，请先检查飞书。',kind:'error'}}))}}
watch(()=>snapshot.value.workspaceId,read)
onMounted(()=>{snapshot.value=feishuWorkspace.getSnapshot();stop=watchFeishuWorkspace(feishuWorkspace);read();window.addEventListener('calmy-feishu-today',read)})
onUnmounted(()=>{stop?.();window.removeEventListener('calmy-feishu-today',read)})
</script>
<template>
  <div class="feishu-page"><header class="page-head"><div><p class="eyebrow">今天 · 飞书 · {{date}}</p><h1 class="font-title">今天，先做一件事</h1><p>从飞书任务中选 1 项主任务、最多 2 项备选。选择只保存在本机，不会修改任务截止日期。</p></div></header>
    <section class="feishu-read-state" aria-label="飞书连接状态"><span role="status">{{statusText()}}</span><button class="app-button" :disabled="snapshot.loading||snapshot.saving" @click="feishuWorkspace.refresh()">刷新</button></section>
    <section v-if="snapshot.error" class="beryl-card empty-state" role="alert"><b>飞书连接暂不可用</b><p>{{snapshot.error}}</p><small>{{snapshot.cacheUpdatedAt?'下方内容来自本机缓存，当前只能查看，不能修改飞书数据。':'没有可显示的本机缓存；连接恢复后可重新读取飞书数据。'}}</small><p><RouterLink to="/app/admin">检查 Worker 地址与同步密码</RouterLink></p></section><p v-if="snapshot.writeError" role="alert">{{snapshot.writeError}}</p><p v-if="message" role="status">{{message}}</p>
    <section class="feishu-today-focus" aria-label="今天选择的飞书任务"><div v-for="(record,index) in selected" :key="record.record_id"><h2>{{index===0?'现在先做':'有余力再做'}}</h2><article class="task-board-card beryl-card"><div class="task-board-card-top"><span class="action-status">{{label(record,'status')||'未设置'}}</span><span>飞书</span></div><h3>{{title(record)}}</h3><small>{{label(record,'project')||'未关联项目'}} · {{dateText(field(record,'due'))}}</small><label>状态<CalmySelect :id="`today-feishu-status-${record.record_id}`" :ariaLabel="`${title(record)}状态`" :model-value="label(record,'status')||'未设置'" :options="taskStatusOptions(record)" :disabled="!snapshot.ready||snapshot.saving||!selectableStatuses.length" compact @change="changeStatus(record,$event)"/></label><div class="feishu-card-actions"><button v-if="index>0" class="app-button" :disabled="!snapshot.ready" @click="save([record.record_id,...ids.filter(id=>id!==record.record_id)])">设为主任务</button><button class="app-button" :disabled="!snapshot.ready" @click="save(ids.filter(id=>id!==record.record_id))">移出今天</button></div></article></div><section v-if="!selected.length" class="beryl-card empty-state"><b>先选一项值得做的任务</b><p>无日期的任务也能加入今天，不必先填完整表单。</p></section><p v-for="id in missing" :key="id" class="beryl-card feishu-message">所选任务 {{id}} 已删除或不在当前视图中。<button class="app-button" @click="save(ids.filter(item=>item!==id))">移除引用</button></p></section>
    <details class="beryl-card feishu-candidates" :open="!ids.length"><summary>从飞书选择任务（已选 {{ids.length}}/3）</summary><input aria-label="搜索今日候选飞书任务" placeholder="搜索任务…" v-model="query"><div class="feishu-record-grid"><article v-for="record in candidates" :key="record.record_id" class="beryl-card feishu-record-card"><h3>{{title(record)}}</h3><p>{{label(record,'project')||'未关联项目'}} · {{label(record,'status')||'未设置'}}</p><button class="app-button" :disabled="!snapshot.ready||ids.length>=3" @click="save([...ids,record.record_id])">加入今天</button></article></div><p v-if="snapshot.ready&&!candidates.length">没有匹配的待选任务。</p></details>
    <h2>快速新增</h2><section class="beryl-card feishu-composer" aria-label="创建飞书任务"><label>任务标题<textarea aria-label="飞书任务标题" v-model="draft" :disabled="snapshot.saving" @keydown.ctrl.enter.prevent="create" @keydown.meta.enter.prevent="create" placeholder="只写一个可以去做的下一步…"/></label><div class="create-row"><label>项目（可选）<CalmySelect id="today-feishu-project" ariaLabel="飞书任务关联项目" v-model="projectId" :options="projectOptions" :disabled="snapshot.saving||!!snapshot.tableErrors.projects||!projectField||![18,21].includes(projectField.type)"/></label><button class="app-button primary" :disabled="!draft.trim()||!snapshot.ready||!titleField||snapshot.saving" @click="create">{{snapshot.saving?'正在保存…':'保存到飞书并加入今天'}}</button></div><p v-if="snapshot.ready&&!titleField" role="alert">任务标题字段缺失或类型已变化，暂不能新增。</p><small>不要求日期或优先级；不会另建本地行动。Ctrl / ⌘ + Enter 保存。</small></section>
  </div>
</template>
