<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import { createAsyncCollectionRepository } from '@/core/repository'
import { fmtDate, nextId } from '@/core/storage'
import { registerUndo } from '@/core/undo'
import { withSaveState } from '@/core/save-state'
import { linkFinanceToCase } from '@/application'
import { caseAsyncRelationRepository, caseAsyncRepository } from '@/domain/case/repository'
interface FinanceItem { id: string; type: 'income' | 'expense' | string; amount?: number; amountCents?: number; category: string; note: string; date: string }
const repository = createAsyncCollectionRepository<FinanceItem>('finance', item => item.id)
const categories = ['餐饮', '交通', '购物', '娱乐', '住房', '工资', '理财', '医疗', '学习', '其他']
const items = ref<FinanceItem[]>([]); const type = ref<'expense' | 'income'>('expense'); const category = ref(''); const amount = ref(''); const note = ref(''); const filter = ref<'all' | 'income' | 'expense'>('all'); const busyId = ref(''); const loading = ref(true); const error = ref('')
function toast(message: string, kind: 'success' | 'warning' | 'error' = 'success') { window.dispatchEvent(new CustomEvent('beryl-toast', { detail: { message, kind } })) }
function parseAmountCents(value: string): number | null { const normalized = value.trim(); if (!/^\d+(?:\.\d{1,2})?$/.test(normalized)) return null; const [whole, fraction = ''] = normalized.split('.'); const cents = Number(whole) * 100 + Number(fraction.padEnd(2, '0')); return Number.isSafeInteger(cents) && cents > 0 ? cents : null }
function amountCents(item: Pick<FinanceItem, 'amount' | 'amountCents'>) { const stored = Number(item.amountCents); if (Number.isSafeInteger(stored)) return stored; const legacy = item.amount == null ? null : parseAmountCents(String(item.amount)); return legacy ?? Math.round(Number(item.amount || 0) * 100) }
function formatCents(cents: number) { const sign = cents < 0 ? '-' : ''; const absolute = Math.abs(Math.trunc(cents)); return `${sign}${Math.floor(absolute / 100).toLocaleString('zh-CN')}.${String(absolute % 100).padStart(2, '0')}` }
async function refresh() { loading.value = true; error.value = ''; try { items.value = (await repository.list()).filter(item => item?.id).map(item => ({ ...item, type: item.type || 'expense', category: item.category || '其他', note: item.note || '', date: item.date || '' })) } catch (cause) { error.value = cause instanceof Error ? cause.message : '财务数据读取失败' } finally { loading.value = false } }
const stats = computed(() => items.value.reduce((result, item) => { const cents = amountCents(item); if (item.type === 'income') result.income += cents; else result.expense += cents; return result }, { income: 0, expense: 0 }))
const visibleItems = computed(() => filter.value === 'all' ? items.value : items.value.filter(item => item.type === filter.value))
async function add() { const cents = parseAmountCents(amount.value); if (cents == null) { toast('请输入大于 0 且最多两位小数的金额', 'warning'); return }; try { await withSaveState(() => repository.create({ id: nextId(), type: type.value, amountCents: cents, amount: cents / 100, category: category.value.trim() || '其他', note: note.value.trim(), date: fmtDate(Date.now()) })); amount.value = ''; note.value = ''; await refresh(); window.dispatchEvent(new CustomEvent('beryl-data-synced')); toast(type.value === 'income' ? '已记录收入' : '已记录支出') } catch (cause) { toast(cause instanceof Error ? cause.message : '财务记录保存失败', 'error') } }
async function remove(item: FinanceItem) { if (!window.confirm(`确定删除「${item.category}」${item.note ? `（${item.note}）` : ''}的 ${formatCents(amountCents(item))} 元记录吗？删除后可在短时间内撤销。`)) return; busyId.value = item.id; try { await withSaveState(async () => { const list = await repository.list(); const index = list.findIndex(candidate => String(candidate.id) === item.id); if (index < 0) throw new Error('记录已不存在，请刷新后重试'); const [removed] = list.splice(index, 1); if (!await repository.remove(item.id)) throw new Error('删除失败，原记录未改变'); registerUndo('finance', removed, index, item.id) }); await refresh(); window.dispatchEvent(new CustomEvent('beryl-data-synced')); toast('财务记录已删除，可在提示出现后撤销') } catch (cause) { toast(cause instanceof Error ? cause.message : '删除失败', 'error') } finally { busyId.value = '' } }
const relationCases = ref<Record<string, Array<{ id: string; title: string }>>>({}); const relationValues = ref<Record<string, string>>({})
async function loadRelation(item: FinanceItem) { try { const [cases, relations] = await Promise.all([caseAsyncRepository.list(), caseAsyncRelationRepository.listForTarget('transaction', item.id)]); relationCases.value[item.id] = cases.filter(candidate => candidate.status !== 'archived').map(candidate => ({ id: candidate.id, title: candidate.title })); relationValues.value[item.id] = relations[0]?.caseId || '' } catch (cause) { toast(cause instanceof Error ? cause.message : '课题关联读取失败', 'warning') } }
async function saveRelation(item: FinanceItem, value: string) { try { await withSaveState(() => linkFinanceToCase({ caseId: value, transactionId: item.id, phase: 'earth', commandId: nextId() })); relationValues.value[item.id] = value; window.dispatchEvent(new CustomEvent('beryl-data-synced')); toast(value ? '已关联课题' : '已取消课题关联') } catch (cause) { toast(cause instanceof Error ? cause.message : '课题关联保存失败', 'error') } }
watch(visibleItems, values => values.forEach(item => { void loadRelation(item) }))
const onSync = () => void refresh()
onMounted(() => { void refresh(); window.addEventListener('beryl-data-synced', onSync) })
onUnmounted(() => window.removeEventListener('beryl-data-synced', onSync))
onUnmounted(() => window.removeEventListener('beryl-data-synced', onSync))
</script>
<template>
  <div class="finance-page"><header class="page-head"><div><p class="eyebrow">财务 · 收支</p><h1 class="font-title">财务</h1><p>记录每一笔现金流，先看清发生了什么，再决定下一步。</p></div><span class="load-pill">{{loading ? '正在读取…' : `${items.length} 条记录`}}</span></header>
    <section v-if="error" class="beryl-card empty-state" role="alert"><b>财务数据暂时无法读取</b><p>{{error}}</p><button class="app-button" type="button" @click="refresh">重试</button></section>
    <section class="stats-grid" aria-label="财务汇总"><article class="stat-card beryl-card"><small>收入</small><b class="finance-income">{{formatCents(stats.income)}}</b><span>元</span></article><article class="stat-card beryl-card"><small>支出</small><b class="finance-expense">{{formatCents(stats.expense)}}</b><span>元</span></article><article class="stat-card beryl-card"><small>结余</small><b class="finance-balance">{{formatCents(stats.income - stats.expense)}}</b><span>元</span></article></section>
    <form class="beryl-card admin-block finance-form" @submit.prevent="add"><div class="panel-head"><div><p class="eyebrow">CASH FLOW</p><h2 class="font-title">记一笔</h2></div><span>金额以分为单位保存</span></div><div class="create-row"><select aria-label="收支类型" v-model="type"><option value="expense">支出</option><option value="income">收入</option></select><input list="finance-categories" aria-label="财务分类" v-model="category" placeholder="分类，例如餐饮"><input aria-label="金额" inputmode="decimal" v-model="amount" placeholder="金额，例如 12.50"></div><div class="create-row finance-note-row"><input aria-label="财务备注" v-model="note" placeholder="备注（可选）"><button class="primary" type="submit" :disabled="loading">添加记录</button></div><datalist id="finance-categories"><option v-for="item in categories" :key="item" :value="item"/></datalist></form>
    <div class="section-title finance-list-head"><h2 class="font-title">记录</h2><select aria-label="财务记录筛选" v-model="filter"><option value="all">全部</option><option value="income">收入</option><option value="expense">支出</option></select></div>
    <section class="history-list" aria-live="polite"><div v-if="loading" class="empty-state" role="status">正在读取财务记录…</div><template v-else><article v-for="item in visibleItems" :key="item.id" class="beryl-card history-card finance-item"><div class="panel-head"><div><p class="eyebrow">{{item.type === 'income' ? 'INCOME · 收入' : 'EXPENSE · 支出'}}</p><h3 class="font-title">{{item.category}}</h3></div><time>{{item.date || '日期未知'}}</time></div><div class="finance-item-body"><p>{{item.note || '没有备注'}}</p><strong :class="item.type === 'income' ? 'finance-income' : 'finance-expense'">{{item.type === 'income' ? '+' : '-'}}{{formatCents(amountCents(item))}} 元</strong></div><div class="finance-item-actions"><select class="case-link" :aria-label="`关联${item.category}课题`" :value="relationValues[item.id] || ''" @change="saveRelation(item, ($event.target as HTMLSelectElement).value)"><option value="">关联课题</option><option v-for="candidate in relationCases[item.id] || []" :key="candidate.id" :value="candidate.id">◈ {{candidate.title}}</option></select><button class="app-button danger" :disabled="busyId === item.id || loading" @click="remove(item)" :aria-label="`删除${item.category}财务记录`">{{busyId === item.id ? '删除中…' : '删除'}}</button></div></article><div v-if="!visibleItems.length" class="empty-state">还没有匹配的财务记录。记录第一笔收入或支出，开始看见现金流。</div></template></section>
  </div>
</template>
