<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { addActionToToday, openToday } from '@/application'
import { withSaveState } from '@/core/save-state'
import { todayKey } from '@/core/storage'
import { actionAsyncRepository } from '@/domain/action/repository'
import type { ActionItem } from '@/domain/action/model'
import type { Matter } from '@/domain/matter/model'
import { todayAsyncRepository } from '@/domain/today/repository'
import type { TodayLoad, TodayPlan } from '@/domain/today/model'
import { recordAsyncRepository } from '@/domain/record/repository'
import type { JournalCategory } from '@/domain/record/model'
import { isJournalCategory } from '@/domain/record/model'
import { listActionRecordDocumentsAsync, type RealityDocument } from '@/domain/reality'
import WorkspaceSourceBar from '@/vue/shell/WorkspaceSourceBar.vue'
import FeishuToday from '@/vue/pages/FeishuToday.vue'
import CalmySelect from '@/vue/components/CalmySelect.vue'

const date = todayKey()
const router = useRouter()
function navigate(path: string) { void router.push(path) }
const source = ref<'local'|'feishu'>(readSource())
function readSource(): 'local'|'feishu' { try { return localStorage.getItem('calmy:workspace:source')==='feishu'?'feishu':'local' } catch { return 'local' } }
function syncSource() { source.value=readSource() }
const loading = ref(true); const saving = ref(false); const plan = ref<TodayPlan>(); const actions = ref<ActionItem[]>([]); const matters = ref<Matter[]>([]); const protect = ref(''); const letGo = ref(''); const actionTitle = ref(''); const matterId = ref(''); const recordBody = ref(''); const journalCategory = ref<JournalCategory>('fact'); const realityMessage = ref(''); const error = ref('')
const recent = ref<RealityDocument[]>([]); const recentLoading = ref(true); const recentError = ref('')
const availableActions = computed(() => actions.value.filter(item => item.status !== 'cancelled'))
const matterOptions = computed(() => [{ value: '', label: '不关联事项' }, ...matters.value.filter(item => item.status !== 'archived').map(item => ({ value: item.calmyId, label: item.title }))])
const primaryAction = computed(() => { const focused = plan.value?.focusActionIds || []; return availableActions.value.find(item => focused.includes(item.calmyId) && ['planned','in_progress'].includes(item.status)) || availableActions.value.find(item => ['in_progress','planned'].includes(item.status)) })
const extraLimit = computed(() => plan.value?.load === 'bad' ? 0 : plan.value?.load === 'tired' ? 1 : 2)
const extraActions = computed(() => availableActions.value.filter(item => item.calmyId !== primaryAction.value?.calmyId && item.status !== 'done').slice(0,extraLimit.value))
const analysis = computed(() => plan.value?.review.analysis || plan.value?.why || '还有什么没有看清？可以把问题带到复盘里，不必现在解决。')
const narrative = computed(() => { if (plan.value?.load === 'bad') return '今天先照顾承载，不需要追赶。'; if (plan.value?.load === 'tired') return '今天在降低承载，保留一件真正重要的事就够了。'; if (primaryAction.value?.status === 'in_progress') return '这一件事正在现实中展开，先把注意力放回手边。'; if (primaryAction.value?.status === 'done') return '这一轮已经有了真实发生，可以停下来让它结束。'; return '这一天还在展开，先保留一个可以去现实中做的下一步。' })
function toast(message: string, kind: 'success'|'warning'|'error'='success') { window.dispatchEvent(new CustomEvent('beryl-toast',{detail:{message,kind}})) }
async function refresh() { loading.value=true;error.value='';try{const opened=await openToday(date);plan.value=opened.plan;actions.value=opened.actions;matters.value=opened.matters;protect.value=opened.plan.mustProtect.join('\n');letGo.value=opened.plan.letGo.join('\n')}catch(cause){error.value=cause instanceof Error?cause.message:'Today 读取失败';toast(error.value,'error')}finally{loading.value=false} }
async function refreshRecent() { recentLoading.value=true;recentError.value='';try{const from=new Date(`${date}T00:00:00`).getTime();const to=new Date(`${date}T23:59:59.999`).getTime();recent.value=(await listActionRecordDocumentsAsync({types:['record'],from,to,limit:8})).slice(0,3)}catch{recentError.value='今天的记录暂时无法读取。'}finally{recentLoading.value=false} }
async function savePlan(patch: Partial<TodayPlan>) { if(!plan.value)return;saving.value=true;try{const next=await withSaveState(()=>todayAsyncRepository.update(date,patch,plan.value!.revision));plan.value=next;protect.value=next.mustProtect.join('\n');letGo.value=next.letGo.join('\n');toast('已保存到本地')}catch(cause){toast(cause instanceof Error?cause.message:'保存失败','error')}finally{saving.value=false} }
async function addAction() { if(!plan.value||!actionTitle.value.trim()){toast('先写下一个现实行动','warning');return}try{await withSaveState(()=>addActionToToday({title:actionTitle.value,date,matterId:matterId.value||undefined,plan:plan.value!}));actionTitle.value='';matterId.value='';await refresh();toast('行动已加入今天')}catch(cause){toast(cause instanceof Error?cause.message:'添加行动失败','error')} }
async function goToReality(item: ActionItem) { try{if(item.status==='planned')await withSaveState(()=>actionAsyncRepository.start(item.calmyId,item.revision));realityMessage.value='可以关闭 Calmy，去现实中做这件事。回来后再记录真实发生了什么。';await refresh()}catch(cause){toast(cause instanceof Error?cause.message:'行动状态更新失败','error')} }
function goToPrimaryAction() { const item = primaryAction.value; if (item) void goToReality(item) }
async function toggleAction(item: ActionItem) { try{if(item.status==='done')await withSaveState(()=>actionAsyncRepository.reopen(item.calmyId,item.revision));else await withSaveState(()=>actionAsyncRepository.complete(item.calmyId,undefined,item.revision));await refresh()}catch(cause){toast(cause instanceof Error?cause.message:'行动更新失败','error')} }
async function addRecord() { if(!recordBody.value.trim()){toast('先写下今天实际发生了什么','warning');return}try{await withSaveState(()=>recordAsyncRepository.create({body:recordBody.value,type:'fact',journalCategory:journalCategory.value}));recordBody.value='';await refresh();await refreshRecent();toast('已保存现实记录')}catch(cause){toast(cause instanceof Error?cause.message:'记录失败','error')} }
function setLoad(value: TodayLoad|null) { void savePlan({load:value}) }
function saveBoundaries() { void savePlan({mustProtect:protect.value.split(/\r?\n/).map(item=>item.trim()).filter(Boolean),letGo:letGo.value.split(/\r?\n/).map(item=>item.trim()).filter(Boolean)}) }
function scrollToAction() { document.querySelector<HTMLInputElement>('[aria-label="新增现实行动"]')?.scrollIntoView({behavior:'smooth',block:'center'}) }
const recentEvent = 'calmy-today-recent-refresh'
onMounted(()=>{void refresh();void refreshRecent();window.addEventListener(recentEvent,refreshRecent);window.addEventListener('calmy-workspace-source',syncSource);window.addEventListener('storage',syncSource)})
onUnmounted(()=>{window.removeEventListener(recentEvent,refreshRecent);window.removeEventListener('calmy-workspace-source',syncSource);window.removeEventListener('storage',syncSource)})
</script>
<template>
  <div class="today-page attention-today-page tactile-today-workspace">
    <WorkspaceSourceBar />
    <FeishuToday v-if="source==='feishu'" />
    <template v-else>
    <section class="today-page-status" data-today-region="page-status"><header class="today-minimal-heading"><h1>今天</h1><time :datetime="date">{{date}}</time><span v-if="loading||saving" role="status">{{loading?'读取中…':'正在保存…'}}</span></header><section v-if="error" class="beryl-card empty-state" role="alert"><b>今天的数据暂时无法读取</b><p>{{error}}</p><button class="app-button" @click="refresh">重试</button></section></section>
    <section class="today-journal-stack" data-today-region="today-journal" aria-label="今天的记录">
      <div class="today-capture-region"><section class="record-composer" aria-label="记录今天"><textarea rows="6" aria-label="记录原文" v-model="recordBody" placeholder="写下今天的想法或事实…"/><div class="record-controls"><div class="journal-category" role="group" aria-label="记录类别" :data-selected-category="journalCategory"><button type="button" :aria-pressed="journalCategory==='mind'" @click="journalCategory='mind'">心</button><button type="button" :aria-pressed="journalCategory==='fact'" @click="journalCategory='fact'">事实</button></div><button class="app-button capture-submit" type="button" aria-label="记录" @click="addRecord">记录</button></div></section></div>
      <div class="today-records-region"><section class="recent-records-panel" aria-labelledby="today-recent-title"><div class="recent-records-heading"><h2 id="today-recent-title">今天的记录</h2><button class="quiet-link" type="button" @click="navigate('/app/review')">回顾</button></div><p v-if="recentLoading" class="recent-records-message" role="status">正在读取今天的记录…</p><p v-else-if="recentError" class="recent-records-message" role="status">{{recentError}}</p><div v-else-if="recent.length" class="recent-record-list"><article v-for="item in recent" :key="`${item.entityType}-${item.id}`" class="recent-record-row"><time :datetime="new Date(item.occurredAt??item.updatedAt).toISOString()">{{new Date(item.occurredAt??item.updatedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}}</time><b>{{item.title||item.body||'未命名记录'}}</b><span v-if="isJournalCategory(item.journalCategory)" class="journal-category-badge">{{item.journalCategory==='mind'?'心':'事实'}}</span></article></div><p v-else class="recent-records-message">还没有记录。保存第一条现实记录后，会显示在这里。</p></section></div>
    </section>
    <details class="today-other" data-today-region="other-modules"><summary>其他</summary><div class="today-other-content">
      <div class="today-focus-region"><section class="now-panel focus-surface beryl-card" aria-labelledby="now-title"><div class="focus-panel-copy"><div class="focus-panel-label"><span aria-hidden="true"></span><p>此刻最重要的事</p></div><div v-if="primaryAction" class="primary-action-card action-card"><div class="primary-action-copy"><span :class="['action-status',primaryAction.status]">{{primaryAction.status==='planned'?'待开始':primaryAction.status==='in_progress'?'进行中':primaryAction.status==='done'?'已完成':primaryAction.status}}</span><h2 id="now-title">{{primaryAction.title}}</h2><p>{{primaryAction?.matterId?matters.find(item=>item.calmyId===primaryAction?.matterId)?.title:'把注意力放回现实中的下一步'}}</p></div><button class="app-button primary reality-button" data-primary-action @click="goToPrimaryAction">{{primaryAction?.status==='in_progress'?'继续去现实中做':'去现实中做'}}</button></div><div v-else class="attention-empty"><div><h2 id="now-title">接下来，做一件小事</h2><p>今天还没有需要投入的主行动。先写下一个可以开始的动作。</p></div><button class="app-button primary" data-primary-action @click="scrollToAction">写下第一步</button></div><p v-if="realityMessage" class="reality-message" role="status">{{realityMessage}}</p></div><div class="extra-action-section"><div class="section-title"><h3>有余力再做</h3><span>最多 2 条</span></div><article v-for="item in extraActions" :key="item.calmyId" class="attention-action-row"><div><span :class="['action-status',item.status]">{{item.status==='planned'?'待开始':item.status==='in_progress'?'进行中':item.status==='done'?'已完成':item.status}}</span><b>{{item.title}}</b></div><button @click="toggleAction(item)">{{item.status==='done'?'重新打开':'完成'}}</button></article><p v-if="!extraActions.length" class="muted">暂时没有额外行动，留一点空白也是选择。</p></div></section></div>
      <div class="today-body-region"><section class="body-state-panel beryl-card" aria-labelledby="body-state-title"><div><p class="eyebrow">BODY · 可跳过</p><h2 id="body-state-title" class="font-title">现在的身体状态</h2><small>{{plan?.load==='good'?'可以多留一点余力':plan?.load==='normal'?'保持当前承载':plan?.load==='tired'?'优先保留一件事':plan?.load==='bad'?'可以关闭所有建议':'不记录也可以继续'}}</small></div><div class="body-state-options" role="group" aria-label="身体状态"><button v-for="[value,label] in [['good','很好'],['normal','正常'],['tired','疲惫'],['bad','明显不舒服']]" :key="value" :class="{on:plan?.load===value}" :aria-pressed="plan?.load===value" :disabled="saving" @click="setLoad(value as TodayLoad)">{{label}}</button><button :class="{on:!plan?.load}" :aria-pressed="!plan?.load" :disabled="saving" @click="setLoad(null)">不记录</button></div></section></div>
      <div class="today-context-region"><aside class="attention-side-column"><section class="think-panel beryl-card" aria-labelledby="think-title"><div class="panel-head"><div><p class="eyebrow">THINK · 可展开</p><h2 id="think-title" class="font-title">思考</h2></div><button class="quiet-link" type="button" @click="navigate('/app/review')">打开复盘 →</button></div><p>{{analysis}}</p><small>AI、资料与相关记录只在你主动展开时出现。</small><button class="quiet-link flow-entry-link" type="button" @click="navigate('/app/flow')">带着问题进探索 →</button></section><section class="trajectory-panel beryl-card" aria-labelledby="trajectory-title"><div class="panel-head"><div><p class="eyebrow">TRAJECTORY · 叙事</p><h2 id="trajectory-title" class="font-title">轨迹</h2></div><button class="quiet-link" type="button" @click="navigate('/app/review')">看证据 →</button></div><p class="trajectory-narrative">{{narrative}}</p><div class="trajectory-evidence"><span v-for="item in actions.slice(0,3)" :key="item.calmyId"><i :class="['trajectory-dot',item.status]"></i>{{item.title}}</span><span v-if="!actions.length">还没有现实记录</span></div></section></aside></div>
      <div class="today-secondary-region"><section class="let-go-panel beryl-card" aria-labelledby="let-go-title"><div class="panel-head"><div><p class="eyebrow">LET GO · 主动放下</p><h2 id="let-go-title" class="font-title">今天主动放下</h2></div><button class="app-button" :disabled="saving" @click="saveBoundaries">保存边界</button></div><div class="two-col"><label>必须守住<textarea aria-label="今天必须守住的事项" v-model="protect" placeholder="例如：先吃饭，再处理消息"/></label><label>今天可以不做<textarea aria-label="今天可以不做的事项" v-model="letGo" placeholder="写下现在可以放下的事"/></label></div></section><section id="today-add-action" class="add-action-panel beryl-card"><div class="panel-head"><div><p class="eyebrow">NEXT ACTION</p><h2 class="font-title">添加一个现实行动</h2></div><span>只写下一步，不用规划整天</span></div><div class="create-row"><input aria-label="新增现实行动" v-model="actionTitle" @keydown.enter="addAction" placeholder="下一步最具体的行动是什么？"/><CalmySelect id="today-action-matter" ariaLabel="行动关联事项" v-model="matterId" :options="matterOptions"/><button class="app-button primary" @click="addAction">加入今天</button></div></section></div>
    </div></details>
    </template>
  </div>
</template>
