<script setup lang="ts">
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { caseRepository } from '@/domain/case/repository'
import { PHASE_META, STATUS_LABEL, type CaseItem, type CaseStatus } from '@/domain/case/model'
const router=useRouter(); const title=ref(''); const query=ref(''); const status=ref<'all'|CaseStatus>('active'); const tick=ref(0)
const all=computed<CaseItem[]>(()=>{void tick.value;return caseRepository.list().slice().sort((a,b)=>b.updatedAt-a.updatedAt)})
const items=computed(()=>all.value.filter(x=>(status.value==='all'||x.status===status.value)&&(!query.value||`${x.title}${x.problem}${x.desiredOutcome}`.toLowerCase().includes(query.value.toLowerCase()))))
const counts=computed(()=>({all:all.value.length,active:all.value.filter(x=>x.status==='active').length,inbox:all.value.filter(x=>x.status==='inbox').length,paused:all.value.filter(x=>x.status==='paused').length,resolved:all.value.filter(x=>x.status==='resolved').length}))
function create(){const v=title.value.trim();if(!v){ElMessage.warning('先写下要解决的现实问题');return};const item=caseRepository.create({title:v});title.value='';router.push('/app/cases/'+item.id)}
</script>
<template>
  <div class="cases-page"><header class="page-head"><div><p class="eyebrow">CASE LIBRARY</p><h1 class="font-title">现实课题</h1><p>每个课题都是一条从问题到行动、判断和复盘的路径。</p></div><div class="head-number"><b>{{ counts.active }}</b><span>正在推进</span></div></header>
  <form class="new-case beryl-card" @submit.prevent="create"><span>◈</span><el-input v-model="title" size="large" placeholder="现在最想解决的一个现实问题是什么？"/><el-button type="primary" native-type="submit">新建课题</el-button></form>
  <div class="toolbar"><div class="filters"><button v-for="item in ([['active','进行中'],['inbox','待梳理'],['paused','暂停'],['resolved','已解决'],['all','全部']] as const)" :key="item[0]" :class="{on:status===item[0]}" @click="status=item[0]">{{ item[1] }} <small>{{ counts[item[0]] }}</small></button></div><el-input v-model="query" class="search" placeholder="搜索课题" clearable /></div>
  <div v-if="items.length" class="cards"><button v-for="item in items" :key="item.id" class="case-card beryl-card hoverable" @click="router.push('/app/cases/'+item.id)"><div class="card-top"><span class="phase">{{ PHASE_META[item.currentPhase].icon }} {{ PHASE_META[item.currentPhase].label }}</span><span class="status">{{ STATUS_LABEL[item.status] }}</span></div><h2 class="font-title">{{ item.title }}</h2><p>{{ item.desiredOutcome || item.problem || '还没有定义目标，打开课题从“木”开始。' }}</p><div class="card-bottom"><span>更新于 {{ new Date(item.updatedAt).toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'}) }}</span><b>进入 →</b></div></button></div>
  <div v-else class="empty"><span>◈</span><h2 class="font-title">这里暂时没有课题</h2><p>{{ query ? '换个关键词试试。' : '把一个模糊的烦恼或目标新建成课题，开始拆解。' }}</p></div></div>
</template>
<style scoped>
.page-head{display:flex;align-items:end;justify-content:space-between;margin:6px 0 28px}.eyebrow{font-size:10px;letter-spacing:.13em;color:var(--scene);font-weight:700;margin:0 0 8px}.page-head h1{font-size:42px;line-height:1;margin:0;letter-spacing:-.035em}.page-head p:last-child{margin:11px 0 0;font-size:13px;color:var(--c-text-2)}.head-number{border-left:1px solid var(--c-border);padding:4px 0 4px 20px;display:grid}.head-number b{font:600 36px/1 var(--font-title);color:var(--scene)}.head-number span{font-size:10px;color:var(--c-text-3);margin-top:5px}.new-case{display:flex;align-items:center;gap:12px;padding:14px 16px}.new-case>span{font-size:24px;color:var(--scene)}.new-case :deep(.el-input){flex:1}.toolbar{margin:28px 0 18px;display:flex;justify-content:space-between;gap:12px}.filters{display:flex;gap:5px;overflow:auto}.filters button{white-space:nowrap;border:0;background:transparent;color:var(--c-text-2);padding:8px 10px;border-radius:8px;font-size:12px;cursor:pointer}.filters button.on{background:var(--scene-soft);color:var(--scene);font-weight:700}.filters small{font-size:10px;opacity:.7}.search{width:190px}.cards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.case-card{min-height:205px;padding:17px;text-align:left;color:var(--c-text);cursor:pointer;display:flex;flex-direction:column}.card-top,.card-bottom{display:flex;align-items:center;justify-content:space-between;gap:8px}.phase{font-size:10px;color:var(--scene);font-weight:700}.status{font-size:10px;color:var(--c-text-3)}.case-card h2{font-size:22px;line-height:1.15;letter-spacing:-.02em;margin:28px 0 8px}.case-card p{font-size:12px;color:var(--c-text-2);line-height:1.65;margin:0;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.card-bottom{margin-top:auto;padding-top:18px;color:var(--c-text-3);font-size:10px}.card-bottom b{color:var(--scene);font-weight:500}.empty{text-align:center;padding:80px 10px;color:var(--c-text-2)}.empty span{font-size:32px;color:var(--scene)}.empty h2{font-size:26px;margin:14px 0 6px}.empty p{font-size:12px;color:var(--c-text-3)}@media(max-width:900px){.cards{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:620px){.page-head h1{font-size:34px}.head-number{display:none}.new-case{flex-wrap:wrap}.new-case :deep(.el-input){width:calc(100% - 40px);flex:none}.new-case .el-button{margin-left:auto}.toolbar{display:block}.search{width:100%;margin-top:12px}.cards{grid-template-columns:1fr}.case-card{min-height:180px}}
</style>
