import { lazy } from 'react'

export const AttentionCapturePage = lazy(() => import('./pages/CapturePage').then(module => ({ default: module.CapturePage })))
export const LegacyAdminHost = lazy(() => import('./LegacyAdminHost').then(module => ({ default: module.LegacyAdminHost })))
export const ReactAdminPage = lazy(() => import('./pages/AdminPage').then(module => ({ default: module.AdminPage })))
export const LibraryPage = lazy(() => import('./pages/LibraryPage').then(module => ({ default: module.LibraryPage })))
export const ScenePage = lazy(() => import('./pages/ScenePage').then(module => ({ default: module.ScenePage })))
export const CalendarPage = lazy(() => import('./pages/CalendarPage').then(module => ({ default: module.CalendarPage })))
export const PeoplePage = lazy(() => import('./pages/PeoplePage').then(module => ({ default: module.PeoplePage })))
export const GraphPage = lazy(() => import('./pages/GraphPage').then(module => ({ default: module.GraphPage })))
export const InboxPage = lazy(() => import('./pages/InboxPage').then(module => ({ default: module.InboxPage })))
export const TasksPage = lazy(() => import('./pages/TasksPage').then(module => ({ default: module.TasksPage })))
export const TaskBoardPage = lazy(() => import('./pages/TaskBoardPage').then(module => ({ default: module.TaskBoardPage })))
export const MemoryPage = lazy(() => import('./pages/MemoryPage').then(module => ({ default: module.MemoryPage })))
export const HabitsPage = lazy(() => import('./pages/HabitsPage').then(module => ({ default: module.HabitsPage })))
export const FinancePage = lazy(() => import('./pages/FinancePage').then(module => ({ default: module.FinancePage })))
export const GoalsPage = lazy(() => import('./pages/GoalsPage').then(module => ({ default: module.GoalsPage })))
export const PomoPage = lazy(() => import('./pages/PomoPage').then(module => ({ default: module.PomoPage })))
export const DiaryPage = lazy(() => import('./pages/DiaryPage').then(module => ({ default: module.DiaryPage })))
export const PostsPage = lazy(() => import('./pages/PostsPage').then(module => ({ default: module.PostsPage })))
export const CyclePage = lazy(() => import('./pages/CyclePage').then(module => ({ default: module.CyclePage })))
export const ProfilePage = lazy(() => import('./pages/ProfilePage').then(module => ({ default: module.ProfilePage })))
